CREATE TABLE "TB_NON_MEMBERS_INFO" (
	"USER_NUMBER"	NUMBER(10)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"USER_SEX"	VARCHAR2(50)		NOT NULL,
	"USER_COUNTRY"	VARCHAR2(50)		NOT NULL,
	"USER_DATE"	VARCHAR2(50)		NOT NULL,
	"USER_PHONE"	VARCHAR2(50)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_RESERVATION" (
	"AIRLINE_RESERVATION_NUMBER"	NUMBER(10)		NOT NULL,
	"ADULT_COUNT"	VARCHAR2(50)		NOT NULL,
	"CHILD_COUNT"	VARCHAR2(50)		NOT NULL,
	"MILE_USE_YN"	CHAR(1)		NOT NULL,
	"SEAT_TYPE"	VARCHAR2(50)		NOT NULL,
	"MEMBER_YN"	CHAR(1)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(255)		NULL,
	"USER_NUMBER"	NUMBER(10)		NULL,
	"OPERATION_ID"	NUMBER(10)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_MEMBERS_INFO" (
	"MEMBER_ID"	VARCHAR2(255)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(255)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(50)		NOT NULL,
	"MEMBER_ENAME"	VARCHAR2(50)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(50)		NOT NULL,
	"MEMBER_SEX"	VARCHAR2(50)		NOT NULL,
	"MEMBER_ADD"	VARCHAR2(255)		NOT NULL,
	"MEMBER_AUTH"	VARCHAR2(50)		NOT NULL,
	"MEMBER_COUNTRY"	VARCHAR2(50)		NOT NULL,
	"MEMBER_MILE"	NUMBER(10)		NOT NULL,
	"MEMBER_DATE"	VARCHAR2(50)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)          NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_CHECKIN" (
	"CHECK_ID"	VARCHAR2(50)		NOT NULL,
	"CHECK_YN"	CHAR(1)		NOT NULL,
	"SEAT_NUMBER"	VARCHAR2(50)		NULL,
	"AIRLINE_RESERVATION_NUMBER"	NUMBER(10)		NOT NULL,
	"PASSPORT_ID"	VARCHAR2(50)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_OPERATION_INFO" (
	"OPERATION_ID"	NUMBER(10)		NOT NULL,
	"AIRLINE"	VARCHAR2(50)		NOT NULL,
	"FLIGHT_NAME"	VARCHAR2(50)		NOT NULL,
	"START_AIRPORT"	VARCHAR2(50)		NOT NULL,
	"FINAL_AIRPORT"	VARCHAR2(50)		NOT NULL,
	"START_TIME"	VARCHAR2(50)		NOT NULL,
	"FINAL_TIME"	VARCHAR2(50)		NOT NULL,
	"OPERATION_DATE"	VARCHAR2(50)		NOT NULL,
	"START_DATE"	VARCHAR2(50)		NOT NULL,
	"FINAL_DATE"	VARCHAR2(50)		NOT NULL,
	"DOMESTIC_INTERNATIONAL"	VARCHAR2(10)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_BAGGAGE" (
	"BAG_NUMBER"	NUMBER(10)		NOT NULL,
	"BAG_COUNT"	NUMBER(2)		NULL,
	"BAG_AREA"	NUMBER(10)		NULL,
	"BAG_WEIGHT"	NUMBER(10)		NULL,
	"BAG_PRICE"	NUMBER(10)		NULL,
	"CHECK_ID"	VARCHAR2(50)		NOT NULL,
	"BAG_YN"	CHAR(1)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_PAY_INFORMATION" (
	"PAY_ID"	NUMBER(10)		NOT NULL,
	"CERTIFIED_ID"	VARCHAR2(50)		NOT NULL,
	"PRODUCT_CODE"	VARCHAR2(50)		NOT NULL,
	"PRODUCT_PRICE"	NUMBER(10)		NOT NULL,
	"PRODUCT_COUNT"	NUMBER(10)		NOT NULL,
    "MILE_PRICE"    NUMBER(10)      NOT NULL,
	"OPERATION_ID"	NUMBER(10)		NOT NULL,
	"AIRLINE_RESERVATION_NUMBER"	NUMBER(10)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_CUSTOMER_SERVICE" (
	"TITLE_ID"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(30)		NOT NULL,
	"RESPONDENT"	VARCHAR2(30)		NULL,
	"CONTENT"	VARCHAR2(100)		NOT NULL,
	"TITLE_CODE_NUMBER"	NUMBER(10)		NOT NULL,
	"ANSWER_YN"	CHAR(1)		NOT NULL,
	"PARENT_BID"	NUMBER(10)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(255)		NOT NULL,
	"INSERT_TIME"  VARCHAR2(30)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(30)          NULL,
	"DELETE_TIME"  VARCHAR2(30)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_PASSPORT" (
	"PASSPORT_ID"	VARCHAR2(50)		NOT NULL,
	"PASSPORT_COUNRTY"	VARCHAR2(50)		NOT NULL,
	"PASSPORT_DATE"	VARCHAR2(50)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(255)		NULL,
	"USER_NUMBER"	NUMBER(10)		NULL,
	"INSERT_TIME"  VARCHAR2(50)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_TIME"  VARCHAR2(50)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);

CREATE TABLE "TB_NOTICE" (
	"NOTICE_ID"	NUMBER(10)		NOT NULL,
	"NOTICE_WRITER"	VARCHAR2(30)		NULL,
	"NOTICE_CONTENT"	VARCHAR2(255)		NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NULL,
	"MEMBER_ID"	VARCHAR2(15)		NOT NULL,
    "INSERT_TIME"  VARCHAR2(30)         NOT NULL,
	"UPDATE_TIME"  VARCHAR2(30)          NULL,
	"DELETE_TIME"  VARCHAR2(30)          NULL,
	"DELETE_YN"  CHAR(1)         NOT NULL
);


ALTER TABLE "TB_NON_MEMBERS_INFO" ADD CONSTRAINT "PK_TB_NON_MEMBERS_INFO" PRIMARY KEY (
	"USER_NUMBER"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "PK_TB_RESERVATION" PRIMARY KEY (
	"AIRLINE_RESERVATION_NUMBER"
);

ALTER TABLE "TB_MEMBERS_INFO" ADD CONSTRAINT "PK_TB_MEMBERS_INFO" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "TB_CHECKIN" ADD CONSTRAINT "PK_TB_CHECKIN" PRIMARY KEY (
	"CHECK_ID"
);

ALTER TABLE "TB_OPERATION_INFO" ADD CONSTRAINT "PK_TB_OPERATION_INFO" PRIMARY KEY (
	"OPERATION_ID"
);

ALTER TABLE "TB_BAGGAGE" ADD CONSTRAINT "PK_TB_BAGGAGE" PRIMARY KEY (
	"BAG_NUMBER"
);

ALTER TABLE "TB_PAY_INFORMATION" ADD CONSTRAINT "PK_TB_PAY_INFORMATION" PRIMARY KEY (
	"PAY_ID"
);

ALTER TABLE "TB_CUSTOMER_SERVICE" ADD CONSTRAINT "PK_TB_CUSTOMER_SERVICE" PRIMARY KEY (
	"TITLE_ID"
);

ALTER TABLE "TB_PASSPORT" ADD CONSTRAINT "PK_TB_PASSPORT" PRIMARY KEY (
	"PASSPORT_ID"
);

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "PK_TB_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

