const korea = [
    {cname:"서울/인천", abbr:"ICN"},
    {cname:"서울/김포", abbr:"GMP"},
    {cname:"제주", abbr:"CJU"},
    {cname:"광주", abbr:"KWJ"},
    {cname:"여수", abbr:"RSU"},
    {cname:"청주", abbr:"CJJ"},
    {cname:"대구", abbr:"TAE"},
    {cname:"부산/김해", abbr:"PUS"},
]

const NortheastAsia = [
    {cname:"광저우", abbr:"CAN"},
    {cname:"구이린", abbr:"KWL"},
    {cname:"나고야", abbr:"NGO"},
    {cname:"난징", abbr:"NKG"},
    {cname:"다롄", abbr:"DLC"},
    {cname:"도쿄/나리타", abbr:"NRT"},
    {cname:"도쿄/하네다", abbr:"HND"},
    {cname:"미야자키", abbr:"KMI"},
    {cname:"베이징", abbr:"PEK"},
    {cname:"삿포로", abbr:"CTS"},
    {cname:"상하이/푸동", abbr:"PVG"},
    {cname:"상하이/홍차오", abbr:"SHA"},
    {cname:"선전", abbr:"SZX"},
    {cname:"센다이", abbr:"SDJ"},
    {cname:"시안", abbr:"XIY"},
    {cname:"옌지", abbr:"YNJ"},
    {cname:"옌청", abbr:"YNZ"},
    {cname:"옌타이", abbr:"YNT"},
    {cname:"오사카/간사이", abbr:"KIX"},
    {cname:"오키나와", abbr:"OKA"},
    {cname:"웨이하이", abbr:"WEH"},
    {cname:"창사", abbr:"CSX"},
    {cname:"창춘", abbr:"CGQ"},
    {cname:"청두/톈푸", abbr:"TFU"},
    {cname:"충칭", abbr:"CKG"},
    {cname:"칭다오", abbr:"TAO"},
    {cname:"타이베이", abbr:"TPE"},
    {cname:"톈진", abbr:"TSN"},
    {cname:"하얼빈", abbr:"HRB"},
    {cname:"항저우", abbr:"HGH"},
    {cname:"홍콩", abbr:"HKG"},
    {cname:"후쿠오카", abbr:"FUK"},
    {cname:"마쓰야마", abbr:"MYJ"},
    {cname:"구마모토", abbr:"KMJ"},
    {cname:"나가사키", abbr:"NGS"},
    {cname:"다카마쓰", abbr:"TAK"},
    {cname:"도야마", abbr:"TOY"},
    {cname:"시즈오카", abbr:"FSZ"},
    {cname:"요나고", abbr:"YGJ"},
    {cname:"우베", abbr:"UBJ"},
    {cname:"히로시마", abbr:"HIJ"},
]

const SoutheastAsia = [
    {cname:"다낭", abbr:"DAD"},
    {cname:"마닐라", abbr:"MNL"},
    {cname:"방콕", abbr:"BKK"},
    {cname:"세부", abbr:"CEB"},
    {cname:"싱가포르", abbr:"SIN"},
    {cname:"자카르타", abbr:"CGK"},
    {cname:"클락/앙헬레스", abbr:"CRK"},
    {cname:"프놈펜", abbr:"PNH"},
    {cname:"하노이", abbr:"HAN"},
    {cname:"호찌민", abbr:"SGN"},
    {cname:"치앙마이", abbr:"CNX"},
    {cname:"델리", abbr:"DEL"},
]
const Americas = [
    {"cname":"로스앤젤레스","abbr":"LAX"},
{"cname":"뉴욕/존 F 케네디","abbr":"JFK"},
{"cname":"샌프란시스코","abbr":"SFO"},
{"cname":"시애틀","abbr":"SEA"},
{"cname":"호놀룰루","abbr":"HNL"},
{"cname":"시카고/오헤어","abbr":"ORD"},
{"cname":"과달라하라","abbr":"GDL"},
{"cname":"그랜 래피스","abbr":"GRR"},
{"cname":"그린베이","abbr":"GRB"},
{"cname":"내슈빌","abbr":"BNA"},
{"cname":"녹스빌","abbr":"TYS"},
{"cname":"뉴올리언스","abbr":"MSY"},
{"cname":"댈러스","abbr":"DFW"},
{"cname":"데이턴","abbr":"DAY"},
{"cname":"덴버","abbr":"DEN"},
{"cname":"드모인","abbr":"DSM"},
{"cname":"디트로이트","abbr":"DTW"},
{"cname":"라스베이거스","abbr":"LAS"},
{"cname":"랜싱","abbr":"LAN"},
{"cname":"렉싱턴","abbr":"LEX"},
{"cname":"로체스터","abbr":"ROC"},
{"cname":"롤리-더럼","abbr":"RDU"},
{"cname":"루이빌","abbr":"SDF"},
{"cname":"리노","abbr":"RNO"},
{"cname":"리치몬드","abbr":"RIC"},
{"cname":"리틀 락","abbr":"LIT"},
{"cname":"리후에","abbr":"LIH"},
{"cname":"마이애미","abbr":"MIA"},
{"cname":"매디슨","abbr":"MSN"},
{"cname":"멕시코시티","abbr":"MEX"},
{"cname":"멤피스","abbr":"MEM"},
{"cname":"몬터레이","abbr":"MRY"},
{"cname":"몬트리올","abbr":"YUL"},
{"cname":"몰린","abbr":"MLI"},
{"cname":"미니애폴리스","abbr":"MSP"},
{"cname":"밀워키","abbr":"MKE"},
{"cname":"버밍엄","abbr":"BHM"},
{"cname":"버팔로","abbr":"BUF"},
{"cname":"벌링턴","abbr":"BTV"},
{"cname":"벤쿠버","abbr":"YVR"},
{"cname":"보스턴","abbr":"BOS"},
{"cname":"보이시","abbr":"BOI"},
{"cname":"워싱턴/벌티모어","abbr":"BWI"},
{"cname":"빅토리아","abbr":"YYJ"},
{"cname":"사우스 밴드","abbr":"SBN"},
{"cname":"새기노","abbr":"MBS"},
{"cname":"새너제이","abbr":"SJC"},
{"cname":"새크라멘토","abbr":"SMF"},
{"cname":"샌디에이고","abbr":"SAN"},
{"cname":"샌안토니오","abbr":"SAT"},
{"cname":"샬럿","abbr":"CLT"},
{"cname":"세인트루이스","abbr":"STL"},
{"cname":"손트레이크시티","abbr":"SLC"},
{"cname":"스포캔","abbr":"GEG"},
{"cname":"스프링필드","abbr":"SGF"},
{"cname":"시더래피즈","abbr":"CID"},
{"cname":"시러큐스","abbr":"SYR"},
{"cname":"신시내티","abbr":"CVG"},
{"cname":"애틀란타","abbr":"ATL"},
{"cname":"애플톤","abbr":"ATW"},
{"cname":"앨버커키","abbr":"ABQ"},
{"cname":"앵커리지","abbr":"ANC"},
{"cname":"야키마","abbr":"YKM"},
{"cname":"에드먼턴","abbr":"YEG"},
{"cname":"오마하","abbr":"OMA"},
{"cname":"오스틴","abbr":"AUS"},
{"cname":"오클라호마 시티","abbr":"OKC"},
{"cname":"오타와","abbr":"YOW"},
{"cname":"올랜도","abbr":"MCO"},
{"cname":"워싱턴/덜레스","abbr":"IAD"},
{"cname":"웨스트팜비치","abbr":"PBI"},
{"cname":"위치토","abbr":"ICT"},
{"cname":"유진","abbr":"EUG"},
{"cname":"인디애나폴리스","abbr":"IND"},
{"cname":"잭슨빌","abbr":"JAX"},
{"cname":"찰스턴","abbr":"CHS"},
{"cname":"카훌루이","abbr":"OGG"},
{"cname":"칸쿤","abbr":"CUN"},
{"cname":"캔자스시티","abbr":"MCI"},
{"cname":"캔튼 애크론","abbr":"CAK"},
{"cname":"캘거리","abbr":"YYC"},
{"cname":"코나","abbr":"KOA"},
{"cname":"콜럼버스","abbr":"CMH"},
{"cname":"콜로라도스프링스","abbr":"COS"},
{"cname":"클리블랜드","abbr":"CLE"},
{"cname":"탬파","abbr":"TPA"},
{"cname":"털사","abbr":"TUL"},
{"cname":"토론토","abbr":"YYZ"},
{"cname":"투손","abbr":"TUS"},
{"cname":"파나마 시티","abbr":"PTY"},
{"cname":"패스코","abbr":"PSC"},
{"cname":"페어뱅크스","abbr":"FAI"},
{"cname":"포트로더데일","abbr":"FLL"},
{"cname":"포트마이어스","abbr":"RSW"},
{"cname":"포틀랜드/OR","abbr":"PDX"},
{"cname":"포틀랜드/ME","abbr":"PWM"},
{"cname":"프레즈노","abbr":"FAT"},
{"cname":"피닉스","abbr":"PHX"},
{"cname":"피츠버그","abbr":"PIT"},
{"cname":"필라델피아","abbr":"PHL"},
{"cname":"헬리팩스","abbr":"YHZ"},
{"cname":"휴스톤","abbr":"IAH"},
{"cname":"산티아고","abbr":"SCL"},
{"cname":"아카풀코","abbr":"ACA"},
{"cname":"보고타","abbr":"BOG"},
{"cname":"레온 과나후아토","abbr":"BJX"},
{"cname":"부에노스 아이레스","abbr":"EZE"},
{"cname":"몬테레이","abbr":"MTY"},
{"cname":"톨리도","abbr":"TOL"},
{"cname":"로체스터","abbr":"RST"},
{"cname":"트래버스시티","abbr":"TVC"},
{"cname":"모빌","abbr":"MOB"},
{"cname":"체터누가","abbr":"CHA"},
{"cname":"플린트","abbr":"FNT"},
{"cname":"풀먼","abbr":"PUW"},
{"cname":"힐로","abbr":"ITO"},
{"cname":"왈라 왈라","abbr":"ALW"},
{"cname":"포트웨인","abbr":"FWA"},
{"cname":"칼라마주","abbr":"AZO"},
{"cname":"잭슨빌","abbr":"JAN"},
{"cname":"라나이","abbr":"LNY"},
{"cname":"코퍼스 크리스티","abbr":"CRP"},
{"cname":"헌츠빌","abbr":"HSV"},
{"cname":"벨링햄","abbr":"BLI"},
{"cname":"이사카","abbr":"ITH"},
{"cname":"피오리아","abbr":"PIA"},
{"cname":"링컨","abbr":"LNK"},
{"cname":"엘 패소","abbr":"ELP"},
{"cname":"샴페인 어바나","abbr":"CMI"},
{"cname":"러벅","abbr":"LBB"},
{"cname":"콜롬비아","abbr":"COU"},
{"cname":"에반스빌","abbr":"EVV"},
{"cname":"웨나치","abbr":"EAT"},
{"cname":"보즈맨","abbr":"BZN"}
]
const Europe = [
{"cname":"프랑크푸르트","abbr":"FRA"},
{"cname":"런던/히드로","abbr":"LHR"},
{"cname":"파리/샤를 드 골","abbr":"CDG"},
{"cname":"로마/다빈치","abbr":"FCO"},
{"cname":"바르셀로나","abbr":"BCN"},
{"cname":"이스탄불","abbr":"IST"},
{"cname":"이즈미르","abbr":"ADB"},
{"cname":"베네치아","abbr":"VCE"},
{"cname":"그라나다","abbr":"GRX"},
{"cname":"그라츠","abbr":"GRZ"},
{"cname":"그란카나리아","abbr":"LPA"},
{"cname":"나폴리","abbr":"NAP"},
{"cname":"뉘른베르크","abbr":"NUE"},
{"cname":"뉴캐슬","abbr":"NCL"},
{"cname":"니스","abbr":"NCE"},
{"cname":"뒤셀도르프","abbr":"DUS"},
{"cname":"드레스덴","abbr":"DRS"},
{"cname":"라이프치히","abbr":"LEJ"},
{"cname":"라코루냐","abbr":"LCG"},
{"cname":"란사로테 섬","abbr":"ACE"},
{"cname":"로도스","abbr":"RHO"},
{"cname":"룩셈부르크","abbr":"LUX"},
{"cname":"류블랴나","abbr":"LJU"},
{"cname":"리스본","abbr":"LIS"},
{"cname":"리옹","abbr":"LYS"},
{"cname":"린츠","abbr":"LNZ"},
{"cname":"마드리드","abbr":"MAD"},
{"cname":"마르세이유","abbr":"MRS"},
{"cname":"말라가","abbr":"AGP"},
{"cname":"맨체스터","abbr":"MAN"},
{"cname":"뮌스터","abbr":"FMO"},
{"cname":"뮌헨","abbr":"MUC"},
{"cname":"밀라노/리나떼","abbr":"LIN"},
{"cname":"밀라노/말펜사","abbr":"MXP"},
{"cname":"바르샤바","abbr":"WAW"},
{"cname":"바젤","abbr":"BSL"},
{"cname":"발렌시아","abbr":"VLC"},
{"cname":"베로나","abbr":"VRN"},
{"cname":"베를린","abbr":"BER"},
{"cname":"벨파스트","abbr":"BHD"},
{"cname":"볼로냐","abbr":"BLQ"},
{"cname":"부다페스트","abbr":"BUD"},
{"cname":"부쿠레슈티","abbr":"OTP"},
{"cname":"부쿠레슈티","abbr":"BBU"},
{"cname":"브레멘","abbr":"BRE"},
{"cname":"브뤼셀","abbr":"BRU"},
{"cname":"비고","abbr":"VGO"},
{"cname":"비엔나","abbr":"VIE"},
{"cname":"빌바오","abbr":"BIO"},
{"cname":"산세바스티안","abbr":"EAS"},
{"cname":"산토리니","abbr":"JTR"},
{"cname":"산티아고 데 콤포스텔라","abbr":"SCQ"},
{"cname":"세비아","abbr":"SVQ"},
{"cname":"슈투트가르트","abbr":"STR"},
{"cname":"스톡홀름","abbr":"ARN"},
{"cname":"스트라스부르","abbr":"XER"},
{"cname":"아테네","abbr":"ATH"},
{"cname":"알리칸테","abbr":"ALC"},
{"cname":"알메리아","abbr":"LEI"},
{"cname":"암스테르담","abbr":"AMS"},
{"cname":"앙카라/에센보아","abbr":"ESB"},
{"cname":"애버딘","abbr":"ABZ"},
{"cname":"에든버러","abbr":"EDI"},
{"cname":"오슬로","abbr":"OSL"},
{"cname":"이비자 섬","abbr":"IBZ"},
{"cname":"자그레브","abbr":"ZAG"},
{"cname":"잘츠부르크","abbr":"SZG"},
{"cname":"제네바","abbr":"GVA"},
{"cname":"취리히","abbr":"ZRH"},
{"cname":"카이세리","abbr":"ASR"},
{"cname":"케르큐라","abbr":"CFU"},
{"cname":"코스","abbr":"KGS"},
{"cname":"코펜하겐","abbr":"CPH"},
{"cname":"퀼른 본","abbr":"CGN"},
{"cname":"클루즈나포카","abbr":"CLJ"},
{"cname":"투린","abbr":"TRN"},
{"cname":"툴루즈","abbr":"TLS"},
{"cname":"트라이안부이아(티미쇼아라)","abbr":"TRSR"},
{"cname":"팔마데마요르카","abbr":"PMI"},
{"cname":"프라하","abbr":"PRG"},
{"cname":"피렌체","abbr":"FLR"},
{"cname":"하노버","abbr":"HAJ"},
{"cname":"함부르크","abbr":"HAM"},
{"cname":"헬싱키","abbr":"HEL"}
]

const Oceanstate = [
    {"cname":"사이판","abbr":"SPN"},
{"cname":"시드니","abbr":"SYD"},
{"cname":"멜버른","abbr":"MEL"},
{"cname":"골드코스트","abbr":"OOL"},
{"cname":"브리즈번","abbr":"BNE"},
{"cname":"애들레이드","abbr":"ADL"},
{"cname":"캐언즈","abbr":"CNS"},
{"cname":"캔버라","abbr":"CBR"},
{"cname":"퍼스","abbr":"PER"},
{"cname":"호바트","abbr":"HBA"},
{"cname":"코프스하버","abbr":"CFS"},
{"cname":"탬워스","abbr":"TMW"},
{"cname":"올버리","abbr":"ABX"},
{"cname":"알미데일","abbr":"ARM"},
{"cname":"포트 매쿠아리","abbr":"PQQ"},
{"cname":"로드하우 아일랜드","abbr":"LDH"},
{"cname":"다윈","abbr":"DRW"},
{"cname":"모리","abbr":"MRZ"},
{"cname":"더보","abbr":"DBO"},
{"cname":"와가와가","abbr":"WGA"}
]
const CentralAsia = [
    {"cname":"울란바타르","abbr":"UBN"},
{"cname":"알마티","abbr":"ALA"},
{"cname":"타슈켄트","abbr":"TAS"}
]

const AirportList = {
    korea,
    NortheastAsia,
    SoutheastAsia,
    Americas,
    Europe,
    Oceanstate,
    CentralAsia
}

export default AirportList;