CREATE TABLE `USER_INFORMATION` (
	`USER_ID`	VARCHAR(14)	NOT NULL	COMMENT '로그인 아이디',
	`USER_PASSWORD`	VARCHAR(13)	NULL,
	`USER_NAME`	VARCHAR(8)	NULL	COMMENT '유저이름',
	`EN_NAME`	VARCHAR(25)	NULL	COMMENT '영문이름',
	`USER_EMAIL`	VARCHAR(25)	NULL	COMMENT '이메일 정보',
	`USER_PHONE`	VARCHAR(14)	NULL	COMMENT '유저 전화번호',
	`USER_SEX`	VARCHAR(1)	NULL	COMMENT '성별',
	`USER_ADD`	VARCHAR(30)	NULL	COMMENT '유저 주소',
	`RIGHT`	NUMBER(15)	NULL	COMMENT '권한',
	`BIRTH_DATE`	VARCHAR(12)	NULL	COMMENT '생년월일',
	`USER_NATIONALITY`	VARCHAR(45)	NULL	COMMENT '국적',
	`MILE_POINT`	NUMBER(20)	NULL
);

CREATE TABLE `PRODUCT_INFORMATION` (
	`NOR_PAY_ID`	NUMBER(15)	NULL	COMMENT '결제 ID',
	`NOR_CERTIFIED_ID`	NUMBER(15)	NULL	COMMENT '인증 ID',
	`NOR_PRODUCT_CODE`	NUMBER(12)	NULL	COMMENT '상품 코드',
	`NOR_PRODUCT_NAME`	VARCHAR(15)	NULL	COMMENT '상품 이름',
	`NOR_PRODUCT_NUMBER`	NUMBER(3)	NULL,
	`NOR_PRODUCT_AMOUNT`	NUMBER(8)	NULL	COMMENT '상품 금액',
	`USER_ID`	VARCHAR(14)	NULL
);

CREATE TABLE `CHECK_IN` (
	`CHECK_RESERVATION_NUMBER`	NUMBER(25)	NULL	COMMENT '예약번호',
	`DOMESTIC_OVERSEAS`	VARCHAR(1)	NULL	COMMENT '국내 해외',
	`TICKET_NUMBER`	NUMBER(15)	NULL	COMMENT '항공권 티켓 번호',
	`BARCODE_ID`	NUMBER(30)	NULL,
	`CHECK_STATE`	VARCHAR(1)	NULL	COMMENT '체크인 상태',
	`SEAT_NUMBER`	NUMBER(5)	NULL,
	`USER_ID`	VARCHAR(14)	NOT NULL	COMMENT '이메일'
);

CREATE TABLE `BAGGAGE` (
	`BAG_NUMBER`	NUMBER(15)	NULL	COMMENT '수화물 번호',
	`BAG_COUNT`	NUMBER(2)	NULL	COMMENT '수화물 개수',
	`BAG_AREA`	VARCHAR(12)	NULL	COMMENT '수화물 면적',
	`BAG_WEIGHT`	NUBMER(10)	NULL	COMMENT '수화물 무게',
	`BAG_BARCODE_NUMBER`	NUMBER(30)	NULL	COMMENT '수화물 바코드 번호',
	`RESERVATION_NUMBER`	VARCHAR(30)	NULL	COMMENT '예약번호',
	`KG_PRICE`	NUMBER(8)	NULL	COMMENT '수화물 가격'
);

CREATE TABLE `RESERVATION` (
	`AIRLINE_RESERVATION_NUMBER`	VARCHAR(30)	NULL,
	`FLIGHT_NAME`	VARCHAR(7)	NULL,
	`USER_ID`	VARCHAR(14)	NOT NULL	COMMENT '유저ID',
	`ROUND_OR_ONE`	VARCHAR(1)	NULL,
	`EN_NAME`	VARCHAR(25)	NULL	COMMENT '영문이름',
	`DEPARTURE`	VARCHAR(15)	NULL	COMMENT '출발일자',
	`ARRIVAL`	VARCHAR(15)	NULL	COMMENT '도착일자',
	`OPERATION_DAY`	VARCHAR(5)	NULL	COMMENT '운항요일',
	`AIRLINE`	VARCHAR(7)	NULL,
	`SEAT_TYPE`	VARCHAR(7)	NULL,
	`ADULT_COUNT`	VARCHAR(2)	NULL,
	`CHILD_COUNT`	VARCHAR(2)	NULL,
	`MILE_USE_STATUS`	VARCHAR(1)	NULL,
	`MEMBERSHIP_STATUS`	VARCHAR(1)	NULL,
	`DOMESTIC_INTERNATIONAL`	VARCHAR(1)	NULL
);

CREATE TABLE `CUSTOMER_SERVICE` (
	`BULLETIN_ID`	NUMBER(5)	NOT NULL,
	`TITLE`	VARCHAR(50)	NULL,
	`USER_ID`	VARCHAR(10)	NULL,
	`RESPONDENT`	VARCHAR(10)	NULL,
	`CONTENT`	VARCHAR(900)	NULL,
	`BULLENTIN_CODE_NUMBER`	NUMBER(15)	NULL,
	`ANSWER_CHECK_STATUS`	VARCHAR(1)	NULL,
	`PARENT_BID`	NUMBER(5)	NULL
);

ALTER TABLE `USER_INFORMATION` ADD CONSTRAINT `PK_USER_INFORMATION` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `PRODUCT_INFORMATION` ADD CONSTRAINT `PK_PRODUCT_INFORMATION` PRIMARY KEY (
	`NOR_PAY_ID`
);

ALTER TABLE `CHECK_IN` ADD CONSTRAINT `PK_CHECK_IN` PRIMARY KEY (
	`CHECK_RESERVATION_NUMBER`
);

ALTER TABLE `BAGGAGE` ADD CONSTRAINT `PK_BAGGAGE` PRIMARY KEY (
	`BAG_NUMBER`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `PK_RESERVATION` PRIMARY KEY (
	`AIRLINE_RESERVATION_NUMBER`
);

ALTER TABLE `CUSTOMER_SERVICE` ADD CONSTRAINT `PK_CUSTOMER_SERVICE` PRIMARY KEY (
	`BULLETIN_ID`
);

